name: Bug report
description: Report a reproducible problem with Geardex
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the details below.
  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: e.g. v0.9.0-beta.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 14.6, Windows 11, Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste logs or drag screenshots here if available.
    validations:
      required: false
