name: Bug report
description: Report a reproducible issue in the GearDex web app, macOS app, or both
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a GearDex bug. This repository tracks issues for both the web app and macOS app, and also hosts official macOS releases.
  - type: dropdown
    id: surface
    attributes:
      label: Where does this issue happen?
      options:
        - Web app (www.geardex.app)
        - macOS app
        - Both web app and macOS app
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App version/build (if known)
      placeholder: e.g. macOS app v1.0.3, or web app context/date
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment details
      placeholder: e.g. Safari 18.0 on macOS 15.2, or macOS 14.7 (Intel)
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste logs or drag screenshots here if available.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submit checklist
      options:
        - label: I searched for existing issues first.
          required: true
        - label: I removed private or sensitive information from logs/screenshots.
          required: true
