name: Feature request
description: Suggest an idea to improve Geardex
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea. Tell us what problem this solves.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain point are you experiencing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like Geardex to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you've tried?
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false
