name: Feature request
description: Suggest an idea to improve GearDex
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea. Tell us what problem this solves for GearDex users.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain point are you experiencing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like GearDex to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you've tried?
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submit checklist
      options:
        - label: I searched for existing feature requests first.
          required: true
